stages:
  - build
  - test
  - deploy

include:
  - project: 'turniere/turniere-infra'
    file: '/ci/pipeline.yaml'

rails spec:
  stage: test
  image: $CI_REGISTRY_IMAGE/test/commits:$CI_COMMIT_SHA
  rules:
    - if: $SKIP_TEST
      when: never
    - if: $CI_PIPELINE_SOURCE != "push"
      when: never
    - changes:
        - '**/*.rb'
        - 'Gemfile'
        - 'Gemfile.lock'
  script:
    - cd /app
    - bundle exec rails db:migrate
    - bundle exec rspec
  artifacts:
    paths:
      - specs_with_runtime.txt
    expire_in: 30 days
