stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/production/Dockerfile  --destination $CI_REGISTRY_IMAGE/production  --destination $CI_REGISTRY_IMAGE/production/commits:$CI_COMMIT_SHA  --destination $CI_REGISTRY_IMAGE/production/branches:$CI_COMMIT_REF_SLUG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/development/Dockerfile --destination $CI_REGISTRY_IMAGE/development --destination $CI_REGISTRY_IMAGE/development/commits:$CI_COMMIT_SHA --destination $CI_REGISTRY_IMAGE/development/branches:$CI_COMMIT_REF_SLUG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/test/Dockerfile        --destination $CI_REGISTRY_IMAGE/test        --destination $CI_REGISTRY_IMAGE/test/commits:$CI_COMMIT_SHA        --destination $CI_REGISTRY_IMAGE/test/branches:$CI_COMMIT_REF_SLUG

rails spec:
  stage: test
  image: registry.gitlab.com/turniere/turniere-backend/test
  script:
    - bundle exec rails db:migrate
    - bundle exec rails spec

kubernetes:
  stage: deploy
  only:
    - master
  image: ruby
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-deploy
  script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/bin/kubectl 
    - kubectl config set-cluster k8s --server="https://kubernetes.default.svc" --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - kubectl config set-credentials sa --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
    - kubectl config set-context local --cluster=k8s --user=sa --namespace=turniere
    - gem install kubernetes-deploy
    - REVISION=$CI_COMMIT_SHA kubernetes-deploy --template-dir kubernetes turniere local
