stages:
  - build
  - test
  - deploy

include:
  - project: 'turniere/turniere-infra'
    file: '/ci/pipeline.yaml'

rails spec:
  stage: test
  image: $CI_REGISTRY_IMAGE/test/commits:$CI_COMMIT_SHA
  rules:
    - changes:
        - '**/*.rb'
        - 'Gemfile'
        - 'Gemfile.lock'
    - if: $SKIP_TEST
      when: never
  script:
    - cd /app
    - bundle exec rails db:migrate
    - bundle exec rails spec
