apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: turniere-backend
spec:
  selector:
    app: turniere-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingress-http
  namespace: turniere-backend
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`api01.turnie.re`)
      kind: Rule
      services:
        - name: backend-service
          port: 3000
      middlewares:
        - name: redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-ingress-https
  namespace: turniere-backend
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`api01.turnie.re`)
      kind: Rule
      services:
        - name: backend-service
          port: 3000
  tls:
    certResolver: default
